apiVersion: v1
kind: Secret
metadata:
  name: betsystem-dotnet-secrets
  labels:
    app: betsystem-dotnet
    secretEnv: dev
    targetApp: betsystem-dev
    namespace: betsystem-dotnet-dev
    owner: NikitaPrachkovski
stringData:
  aspNetEnv: Development

  competitionDb: Host=postgres-betsystem-dev-svc;Port=5432;Database=CompetitionDb_Dev;User Id=postgres;Password=postgres
  competitionDb: Host=postgres-betsystem-dev-svc;Port=5432;Database=ProfileDb_Dev;User Id=postgres;Password=postgres

