apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv
  labels:
    app: {{ .Values.mongo.labels.app }}
    env: {{ .Values.env }}
    targetApp: {{ .Values.targetApp }}
    namespace: {{ .Values.namespace }}
    owner: {{ .Values.owner }}
spec:
  storageClassName: "manual"
  capacity:
    storage: {{ .Values.mongo.volumeCapacity }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.mongo.hostPath }}
