apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  labels:
    app: {{ .Values.mongo.labels.app }}
    env: {{ .Values.env }}
    targetApp: {{ .Values.targetApp }}
    namespace: {{ .Values.namespace }}
    owner: {{ .Values.owner }}
spec:
  selector:
    app: {{ .Release.Name }}-container
  ports:
    - name: mongo-listener
      protocol: TCP
      port: {{ .Values.mongo.servicePort }}
      targetPort: {{ .Values.mongo.containerPort }}
  type: {{ .Values.mongo.service.type }}
